# EEHEMTModelHelper Demo
This notebook demonstrates how to:
1. Create an EEHEMT model helper instance
2. Load init parameters from JSON
3. Simulate and plot I-V curves, then save figures

In [3]:
import sys
from pathlib import Path
import numpy as np

notebook_dir = Path.cwd()
if not (notebook_dir / "eehemt_model_helper.py").exists():
    notebook_dir = notebook_dir / "test" / "eehemt_helper"

if str(notebook_dir) not in sys.path:
    sys.path.insert(0, str(notebook_dir))

from eehemt_model_helper import EEHEMTModelHelper

In [ ]:
project_root = notebook_dir.parents[1]
va_path = notebook_dir / "eehemt114_2.va"
json_path = project_root / "modelcard_and_range/modelcard.json"
save_dir = project_root / "target_curve/demo"

helper = EEHEMTModelHelper(
    va_file_path=str(va_path),
    save_dir=str(save_dir),
    temperature=300,
    curve_condition_name="UGW",
)

print("Model created successfully.")

Model created successfully.


In [5]:
# Define gate-voltage sweep points
vgs = np.round(np.arange(0.0, 1.201, 0.025), 3)

vgs[:5], vgs[-5:]

(array([0.   , 0.025, 0.05 , 0.075, 0.1  ]),
 array([1.1  , 1.125, 1.15 , 1.175, 1.2  ]))

In [6]:
init_params = helper.load_init_params_from_json(str(json_path))
print("Init params loaded from JSON:")
for k, v in init_params.items():
    print(f"{k:>12s} = {v:.6g}")


Init params loaded from JSON:
         Vto = 0.335
         Vgo = 0.556
        Vsat = 0.456
         Vbc = 1.33
       Gmmax = 0.185
          Rd = 1.15
          Rs = 1.9
        Peff = 1.915
        Kapa = 0.059
       Alpha = 0.007


In [7]:
i_sim = helper.simulate_ids_from_json_init(
    json_path=str(json_path),
    vgs=vgs,
    vds_voltage=0.5,
    curve_condition_value=0.5,
    modelcard_updates=None,
)

i_sim[:5]

array([1.42807790e-29, 3.91751197e-28, 1.07465426e-26, 2.94799809e-25,
       8.08696626e-24])

In [ ]:
linear_path = helper.plot_iv_curve(
    vgs=vgs,
    i_sim=i_sim,
    i_meas=None,
    title="I-V Curve (Linear)",
    save_name="iv_curve_linear_demo.png",
    log_y=False,
)

log_path = helper.plot_iv_curve(
    vgs=vgs,
    i_sim=i_sim,
    i_meas=None,
    title="I-V Curve (Log)",
    save_name="iv_curve_log_demo.png",
    log_y=True,
)

print("Linear plot:", linear_path)
print("Log plot:", log_path)

Saved plot to: /home/u5977862/DRL-on-parameter-extraction/result/iv_curve/demo/iv_curve_linear_demo.png
Saved plot to: /home/u5977862/DRL-on-parameter-extraction/result/iv_curve/demo/iv_curve_log_demo.png
Linear plot: /home/u5977862/DRL-on-parameter-extraction/result/iv_curve/demo/iv_curve_linear_demo.png
Log plot: /home/u5977862/DRL-on-parameter-extraction/result/iv_curve/demo/iv_curve_log_demo.png
